export type ToolItem = {
  name: string;
  description: string;
};

// Ordered list used by the public template (custom domains + partner public pages)
export const PARTNER_TOOLS: ToolItem[] = [
  { name: "Academun", description: "Online learning platform" },
  { name: "Ahrefs", description: "SEO and backlink analysis tool" },
  { name: "AlsoAsked", description: "Question suggestions & related queries" },
  { name: "Atria", description: "AI for inspiration and creative optimization" },
  { name: "Brain.fm", description: "Music for productivity" },
  { name: "Canva Pro", description: "Design creation" },
  { name: "CapCut Pro", description: "Video editing" },
  { name: "Chat GPT Plus", description: "Advanced AI language model" },
  { name: "Dinorank", description: "SEO ranking & performance tool" },
  { name: "Dropship.io", description: "Store sales follow-up" },
  { name: "Eleven Labs", description: "Best AI voices" },
  { name: "Envato Element", description: "Marketplace of creative resources for designers and developers" },
  { name: "Exploding Topics", description: "Discovering new trends" },
  { name: "Flair.ai", description: "AI-assisted design and branding tool" },
  { name: "Flaticon", description: "Icon database" },
  { name: "Fliki", description: "Video making" },
  { name: "Foreplay", description: "Ad creation tool" },
  { name: "Freepik", description: "Graphic resources platform, icons, photos" },
  { name: "Fotor", description: "AI image editing" },
  { name: "Gemini + NanoBanana", description: "AI text and task automation + image editing" },
  { name: "Helium 10", description: "Market analysis and product research" },
  { name: "Heygen", description: "AI video creation for UGC & avatars" },
  { name: "Higgsfield", description: "AI video generation and editing" },
  { name: "Hunter", description: "Email finder & verification" },
  { name: "Iconscout", description: "Marketplace of icons and illustrations" },
  { name: "JungleScout", description: "Product research and market analysis for Amazon" },
  { name: "Kalodata", description: "TikTok Shop analysis tool" },
  { name: "Keysearch", description: "SEO keyword research tool" },
  { name: "Keyword Tool", description: "Generate keyword ideas for SEO and PPC campaigns" },
  { name: "Majestic", description: "Backlink analysis and SEO metrics" },
  { name: "Mangools", description: "Suite for SEO research and site analysis" },
  { name: "Midjourney", description: "Image generation" },
  { name: "Niche Scrapper", description: "Extract and analyze profitable niche markets" },
  { name: "OnlyAds", description: "Ad campaign monitoring" },
  { name: "Peeksta", description: "Product search" },
  { name: "PinSpy", description: "Pinterest ad analysis" },
  { name: "Pipiads", description: "Product search on TikTok" },
  { name: "Quetext", description: "Plagiarism detection" },
  { name: "Quillbot", description: "AI-powered paraphrasing tool" },
  { name: "SearchAtlas", description: "SEO research and analysis" },
  { name: "Sell The Trend", description: "Product trend analysis" },
  { name: "Semrush", description: "Comprehensive SEO and competitive research" },
  { name: "SendShort", description: "Short subtitles" },
  { name: "Shophunter", description: "Online store monitoring and analysis" },
  { name: "Similarweb", description: "Website traffic and competitive intelligence" },
  { name: "Storyblocks", description: "Stock media platform" },
  { name: "Text Optimizer", description: "Textual content optimization tool to improve SEO" },
  { name: "Ubersuggest", description: "Keyword research and SEO insights" },
  { name: "Veo 3", description: "Google AI video generator" },
  { name: "Vmake AI", description: "AI video editing (cleanup, enhance, captions)" },
  { name: "Youzign", description: "Graphic design tool" },
  { name: "YourTextGuru", description: "SEO content optimization" },
  { name: "WooRank", description: "SEO analysis and website audit tool" },
];

