// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Resolve env vars safely on client and SSR; if absent, create a no-op client to avoid runtime crash.
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export const SUPABASE_CONFIG_OK =
  typeof SUPABASE_URL === "string" && SUPABASE_URL.startsWith("http") &&
  typeof SUPABASE_PUBLISHABLE_KEY === "string" && SUPABASE_PUBLISHABLE_KEY.length > 40;

const url = SUPABASE_CONFIG_OK ? (SUPABASE_URL as string) : "https://example.supabase.co";
const key = SUPABASE_CONFIG_OK ? (SUPABASE_PUBLISHABLE_KEY as string) : "eyJhbGciOiJIUzI1NiJ9.placeholder";

export const supabase: SupabaseClient<Database, 'public'> =
  createClient<Database, 'public'>(url, key);